Обновлен файл readme, добавлена схема, обновлен cloud-init

diff --git a/project-timeweb/cloud-init.yml b/project-timeweb/cloud-init.yml
--- a/project-timeweb/cloud-init.yml
+++ b/project-timeweb/cloud-init.yml
@@ -6,18 +6,149 @@ users:
     groups: sudo
     sudo: ["ALL=(ALL) NOPASSWD:ALL"]
     ssh_authorized_keys:
-      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINxT15yJYj1cWElTZjjz7iKdPx7y2G8RCCN/SAG8R7nv uname
+      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL7CvuNInbvoucGdJKhgvXS/vbM5PGt3SqhDo00gSOjK uname@desktop-2
 
 package_update: true
 package_upgrade: true
 
 packages:
-  - ufw
+  - fail2ban
+  - wireguard
   - git
   - curl
   - ca-certificates
   - gnupg
+  - qrencode
 
+write_files:
+  - path: /etc/sysctl.d/99-wireguard-forward.conf
+    owner: root:root
+    permissions: '0644'
+    content: |
+      net.ipv4.ip_forward=1
+      net.ipv6.conf.all.forwarding=1
+  
+  - path: /etc/fail2ban/jail.local
+    owner: root:root
+    permissions: '0644'
+    content: |
+      [DEFAULT]
+      bantime  = 864000
+      findtime = 600
+      maxretry = 3
+      banaction = ufw
+
+      [sshd]
+      enabled = true
+      port    = ssh
+      logpath = %(sshd_log)s
+      backend = %(sshd_backend)s
+  
+  - path: /usr/localbin/add-wg-user
+    owner: root:root
+    permissions: '0755'
+    content: |
+      #!/bin/bash
+      set -e
+
+      if [ -z "$1" ]; then
+          echo "Ошибка: Укажите имя пользователя!"
+          echo "Использвание: add-wg-user USER_NAME"
+          exit 1
+      fi
+
+      USERNAME=$1
+      CDIR="/etc/wireguard/clients/$USERNAME"
+
+      if [ -d "$CDIR" ]; then
+          echo "Ошибка: Пользователь $USERNAME уже существует!"
+          exit 1
+      fi
+
+      mkdir -p "$CDIR"
+
+      PRIV_KEY=$(wg genkey)
+      PUB_KEY=$(echo "PRIV_KEY" | wg pubkey)
+      SERVER_PUB_KEY=$(cat /etc/wireguard/server_publickey)
+      SERVER_IP=$(curl -s4 ifconfig.me)
+
+
+----------
+
+      USED_IPS=$(grep -oE "10\.8\.0\.[0-9]+" /etc/wireguard/wg0.conf || true)
+      for i in {2..254}; do
+          if ! echo "$USED_IPS" | grep -q "10.8.0.$i"; then
+              CLIENT_IP="10.8.0.$i"
+              break
+          fi
+      done
+
+      if [ -z "$CLIENT_IP" ]; then
+          echo "Ошибка: В подсети закончились свободные IP!"
+          exit 1
+      fi
+
+      cat <<EOF > "$CDIR/$USERNAME.conf"
+      [Interface]
+      PrivateKey = $PRIV_KEY
+      Address = $CLIENT_IP/32
+      DNS = 1.1.1.1
+
+      [Peer]
+      PublicKey = $SERVER_PUB_KEY
+      Endpoint = $SERVER_IP:51820
+      AllowedIPs = 0.0.0.0/0
+      PersistentKeepalive = 20
+      EOF
+
+      wg set wg0 peer "$PUB_KEY" allowed-ips "$CLIENT_IP/32"
+      
+      cat <<EOF >> /etc/wireguard/wg0.conf
+
+      [Peer]
+      # Name = $USERNAME
+      PublicKey = $PUB_KEY
+      AllowedIPs = $CLIENT_IP/32
+      EOF
+
+      echo "======================================================"
+      echo "Пользователь $USERNAME успешно добавлен!"
+      echo "Конфиг сохранен в: $CDIR/$USERNAME.conf"
+      echo "======================================================"
+      echo "=== QR-КОД ДЛЯ СМАРТФОНА (Сканировать в приложении) ==="
+      qrencode -t ansiutf8 < "$CDIR/$USERNAME.conf"
+      echo "======================================================"
+
+# 4. Последовательный запуск служб и сетевого экрана
+runcmd:
+  # Применяем настройки ядра Linux
+  - sysctl --system
+
+  # Инициализируем WireGuard сервер, генерируем его ключи и стартовый wg0.conf
+  - cd /etc/wireguard/
+  - wg genkey | tee server_privatekey | wg pubkey > server_publickey
+  - |
+    cat <<EOF > wg0.conf
+    [Interface]
+    Address = 10.8.0.1/24
+    ListenPort = 51820
+    PrivateKey = $(cat server_privatekey)
+    PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
+    PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
+    EOF
+  - systemctl enable wg-quick@wg0
+  - systemctl start wg-quick@wg0
+
+  # Включаем и запускаем Fail2ban
+  - systemctl enable fail2ban
+  - systemctl start fail2ban
+
+  # Включаем Firewall (UFW) и жестко закрываем порты
+  - ufw default deny incoming
+  - ufw default allow outgoing
+  - ufw allow 22/tcp comment 'SSH Port'
+  - ufw allow 51820/udp comment 'WireGuard VPN Port'
+  - ufw --force enable
 
 
 
